name: Deploy prod site on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Install NPM Modules
        run: npm install

      - name: Build Project
        run: npm run build --prod

      - name: Build Docker image
        run: docker build -t shortvisions-front -f Dockerfile . --no-cache
      
      - name: Push to GitHub Packages of organization
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: univ-smb-m1-isc-2022/shortvision/develop
          tags: latest
